// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/analytics/{publicID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns referrer URLs, page paths, hit counts, and unique visitor counts for a site within a date range. Useful for backlink analysis.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get analytics data for a site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Opaque public site ID",
                        "name": "publicID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD format, defaults to 30 days ago)",
                        "name": "minDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD format, defaults to today)",
                        "name": "maxDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/site.AnalyticsAPIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/webmentions/{publicID}": {
            "get": {
                "description": "Returns the approved webmentions for the site identified by an opaque public ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webmentions"
                ],
                "summary": "Get approved webmentions for a site",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Opaque public site ID",
                        "name": "publicID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/site.PublicWebMention"
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "site.AnalyticsAPIPeriod": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "site.AnalyticsAPIResponse": {
            "type": "object",
            "properties": {
                "pages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/site.AnalyticsPage"
                    }
                },
                "period": {
                    "$ref": "#/definitions/site.AnalyticsAPIPeriod"
                },
                "referrers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/site.AnalyticsReferrer"
                    }
                },
                "site_url": {
                    "type": "string"
                },
                "total_hits": {
                    "type": "integer"
                },
                "unique_visitors": {
                    "type": "integer"
                }
            }
        },
        "site.AnalyticsPage": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "site.AnalyticsReferrer": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "pages_visited": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "site.PublicWebMention": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your API key with the \"Bearer \" prefix, e.g. \"Bearer abc123...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "mochi.meadow.cafe",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Mochi Analytics API",
	Description:      "API for accessing analytics data from Mochi. Useful for backlink discovery and analysis.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
